name: New PR

on:
  pull_request_target:
    branches:
      - release
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Comment and label
        run: |
          gh pr comment "$PR_NUMBER" --body "Thank you for your contribution, our team will be reviewing this shortly, please be available for any follow up questions or code review feedback!"

      - id: file_changes
        uses: tj-actions/changed-files@v41
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Label PR based on Changes
        env:
          FILES_ADDED: ${{ steps.file_changes.outputs.added_files }}
          FILES_MODIFIED: ${{ steps.file_changes.outputs.modified_files }}
        run: |
          echo "$FILES_ADDED"
          if [[ "$FILES_ADDED" =~ "config.yml" ]]; then
              echo "New config.yml added"
              gh pr edit "$PR_NUMBER" --add-label "new-quickstart"
          elif [[ "$FILES_MODIFIED" =~ quickstarts/.* ]]; then
              echo "Quickstart Updated"
              gh pr edit "$PR_NUMBER" --add-label "improved-quickstart"
          fi
